from ...config import DEFAULT_MEMORYLAYER_MEMORY_SERVICE, MEMORYLAYER_MEMORY_SERVICE
from .._constants import (
    EXT_CACHE_SERVICE,
    EXT_CONTRADICTION_SERVICE,
    EXT_DEDUPLICATION_SERVICE,
    EXT_EMBEDDING_PROVIDER,
    EXT_EXTRACTION_SERVICE,
    EXT_MEMORY_SERVICE,
    EXT_RERANKER_SERVICE,
    EXT_SEMANTIC_TIERING_SERVICE,
    EXT_STORAGE_BACKEND,
)
from .._plugin_factory import make_service_plugin_base

# Recall overfetch multiplier for reranker candidate pool
MEMORYLAYER_MEMORY_RECALL_OVERFETCH = "MEMORYLAYER_MEMORY_RECALL_OVERFETCH"
DEFAULT_MEMORYLAYER_MEMORY_RECALL_OVERFETCH = 3

# Maximum memories discovered via association graph expansion
MEMORYLAYER_MEMORY_MAX_GRAPH_EXPANSION = "MEMORYLAYER_MEMORY_MAX_GRAPH_EXPANSION"
DEFAULT_MEMORYLAYER_MEMORY_MAX_GRAPH_EXPANSION = 50

# Default include_associations for recall (graph expansion enabled by default)
MEMORYLAYER_MEMORY_INCLUDE_ASSOCIATIONS = "MEMORYLAYER_MEMORY_INCLUDE_ASSOCIATIONS"
DEFAULT_MEMORYLAYER_MEMORY_INCLUDE_ASSOCIATIONS = True

# Default traverse_depth for recall (multi-hop graph traversal)
MEMORYLAYER_MEMORY_TRAVERSE_DEPTH = "MEMORYLAYER_MEMORY_TRAVERSE_DEPTH"
DEFAULT_MEMORYLAYER_MEMORY_TRAVERSE_DEPTH = 2


# noinspection PyAbstractClass
MemoryServicePluginBase = make_service_plugin_base(
    ext_name=EXT_MEMORY_SERVICE,
    config_key=MEMORYLAYER_MEMORY_SERVICE,
    default_value=DEFAULT_MEMORYLAYER_MEMORY_SERVICE,
    dependencies=(
        EXT_STORAGE_BACKEND,
        EXT_EMBEDDING_PROVIDER,
        EXT_CACHE_SERVICE,
        EXT_SEMANTIC_TIERING_SERVICE,
        EXT_DEDUPLICATION_SERVICE,
        EXT_RERANKER_SERVICE,
        EXT_CONTRADICTION_SERVICE,
        EXT_EXTRACTION_SERVICE,
    ),
    extra_defaults={
        MEMORYLAYER_MEMORY_RECALL_OVERFETCH: DEFAULT_MEMORYLAYER_MEMORY_RECALL_OVERFETCH,
        MEMORYLAYER_MEMORY_MAX_GRAPH_EXPANSION: DEFAULT_MEMORYLAYER_MEMORY_MAX_GRAPH_EXPANSION,
        MEMORYLAYER_MEMORY_INCLUDE_ASSOCIATIONS: DEFAULT_MEMORYLAYER_MEMORY_INCLUDE_ASSOCIATIONS,
        MEMORYLAYER_MEMORY_TRAVERSE_DEPTH: DEFAULT_MEMORYLAYER_MEMORY_TRAVERSE_DEPTH,
    },
)
