"""MemoryLayer.ai Python SDK - Memory infrastructure for AI agents."""

from .client import MemoryLayerClient
from .constants import (
    MESSAGE_META_APP_WORKSPACE_KEY,
    USER_CHAT_HOME_WORKSPACE,
)
from .exceptions import (
    AuthenticationError,
    AuthorizationError,
    EnterpriseRequiredError,
    MemoryLayerError,
    NotFoundError,
    RateLimitError,
    ServerError,
    ValidationError,
)
from .knowledgebase import (
    KbArticle,
    KbBridge,
    KbCentralNode,
    KbCommunity,
    KbGraphAnalysis,
    KbGraphSnapshot,
    KbGraphStats,
    KbMetadata,
    KnowledgebaseAPI,
    SyncKnowledgebaseAPI,
)
from .models import (
    Association,
    AuthorityContext,
    ChatMessage,
    ChatMessageContent,
    ChatThread,
    ChatThreadWithMessages,
    ContextDelta,
    ContextPack,
    ContextPackItem,
    DatasetColumn,
    DatasetInfo,
    DatasetJobInfo,
    DatasetSliceResult,
    DecompositionResult,
    DocumentInfo,
    DocumentPage,
    Entity,
    EntityRelationInput,
    EntityRelationPath,
    EntityRelationWriteResult,
    EntityResolution,
    JobInfo,
    Memory,
    MemoryListResponse,
    PageSearchResult,
    PrincipalRef,
    RecallResult,
    ReflectResult,
    Session,
    SessionBriefing,
    SessionCheckpoint,
    TokenCreateResult,
    TokenInfo,
    Workspace,
)
from .rpg import (
    RpgAPI,
    RpgConflict,
    RpgConflictResult,
    RpgDeleteResult,
    RpgEdge,
    RpgEdgeInput,
    RpgEnrichmentResult,
    RpgMaintenanceResult,
    RpgNode,
    RpgNodeInput,
    RpgNodeList,
    RpgOverlay,
    RpgOverlayDeleteResult,
    RpgOverlayList,
    RpgSearchResult,
    RpgStatus,
    RpgSubgraph,
    RpgSymbolConflict,
    RpgSymbolConflictResult,
    RpgSyncResult,
    SyncRpgAPI,
)
from .sync_client import SyncMemoryLayerClient, sync_client
from .types import (
    MemorySubtype,
    MemoryType,
    RecallMode,
    RelationshipCategory,
    RelationshipType,
    SearchTolerance,
)

__version__ = "0.2.0"

__all__ = [
    # Main clients
    "MemoryLayerClient",
    "SyncMemoryLayerClient",
    "sync_client",
    # OBO authority types
    "AuthorityContext",
    "PrincipalRef",
    # Stable constants (mirrored from memorylayer-core-python)
    "USER_CHAT_HOME_WORKSPACE",
    "MESSAGE_META_APP_WORKSPACE_KEY",
    # Models
    "Memory",
    "MemoryListResponse",
    "RecallResult",
    "ReflectResult",
    "Association",
    "Session",
    "SessionBriefing",
    "SessionCheckpoint",
    "ContextPack",
    "ContextDelta",
    "ContextPackItem",
    "Workspace",
    # API token models
    "TokenInfo",
    "TokenCreateResult",
    # Entity registry models
    "Entity",
    "EntityResolution",
    "EntityRelationInput",
    "EntityRelationPath",
    "EntityRelationWriteResult",
    # Chat history models
    "ChatMessage",
    "ChatMessageContent",
    "ChatThread",
    "ChatThreadWithMessages",
    "DecompositionResult",
    # Document models (Enterprise)
    "DocumentInfo",
    "DocumentPage",
    "JobInfo",
    "PageSearchResult",
    # Dataset models (Enterprise)
    "DatasetColumn",
    "DatasetInfo",
    "DatasetJobInfo",
    "DatasetSliceResult",
    # Knowledgebase models + namespace
    "KnowledgebaseAPI",
    "SyncKnowledgebaseAPI",
    "KbArticle",
    "KbMetadata",
    "KbGraphStats",
    "KbCommunity",
    "KbCentralNode",
    "KbBridge",
    "KbGraphAnalysis",
    "KbGraphSnapshot",
    # Repository Planning Graph models + namespace
    "RpgAPI",
    "SyncRpgAPI",
    "RpgNodeInput",
    "RpgEdgeInput",
    "RpgNode",
    "RpgEdge",
    "RpgSyncResult",
    "RpgSubgraph",
    "RpgSearchResult",
    "RpgStatus",
    "RpgOverlay",
    "RpgOverlayList",
    "RpgOverlayDeleteResult",
    "RpgDeleteResult",
    "RpgNodeList",
    "RpgConflict",
    "RpgConflictResult",
    "RpgSymbolConflict",
    "RpgSymbolConflictResult",
    "RpgMaintenanceResult",
    "RpgEnrichmentResult",
    # Types
    "MemoryType",
    "MemorySubtype",
    "RecallMode",
    "SearchTolerance",
    "RelationshipType",
    "RelationshipCategory",
    # Exceptions
    "MemoryLayerError",
    "AuthenticationError",
    "AuthorizationError",
    "EnterpriseRequiredError",
    "NotFoundError",
    "ValidationError",
    "RateLimitError",
    "ServerError",
]
