"""Obsidian-compatible markdown renderer for knowledgebase articles."""

import re

from ...models.graph_analysis import Bridge, CentralNode, Community, GraphStats
from .linkcheck import LinkIndex
from .mermaid import build_community_flowchart


class ObsidianRenderer:
    """Renders knowledgebase articles in Obsidian-compatible Markdown.

    Uses [[wikilink]] syntax for cross-references so that articles
    open correctly inside an Obsidian vault.
    """

    # ------------------------------------------------------------------ #
    # Public rendering methods
    # ------------------------------------------------------------------ #

    def render_index(
        self,
        workspace_name: str,
        stats: GraphStats | None,
        communities: list[Community],
        god_nodes: list[CentralNode],
        node_titles: dict[str, str] | None = None,
        link_index: LinkIndex | None = None,
    ) -> str:
        """Render the workspace index article.

        Args:
            workspace_name: Human-readable workspace name
            stats: Optional graph statistics block
            communities: List of detected communities
            god_nodes: Central nodes with high degree/betweenness
            node_titles: Optional mapping of memory_id -> display title for god nodes
            link_index: Articles this run produced; entries without one render as
                plain text rather than as a dangling link

        Returns:
            Markdown string for ``index.md``
        """
        node_titles = node_titles or {}
        lines: list[str] = []

        # OKF v0.1: the bundle-root index is the ONE place an index may carry
        # frontmatter, and only to declare the format version (§11). This makes the
        # exported vault a self-describing, conformant Open Knowledge Format bundle.
        lines.append("---")
        lines.append('okf_version: "0.1"')
        lines.append("---")
        lines.append("")

        lines.append(f"# {workspace_name}")
        lines.append("")
        lines.append("> This knowledgebase was auto-generated by MemoryLayer.")
        lines.append("")

        # Stats block
        if stats:
            lines.append("## Graph Overview")
            lines.append("")
            lines.append("| Metric | Value |")
            lines.append("|--------|-------|")
            lines.append(f"| Memories (nodes) | {stats.node_count} |")
            lines.append(f"| Associations (edges) | {stats.edge_count} |")
            lines.append(f"| Communities | {stats.community_count} |")
            lines.append(f"| Graph density | {stats.density:.3f} |")
            lines.append(f"| Average connections | {stats.avg_degree:.1f} |")
            lines.append(f"| Central nodes | {stats.god_node_count} |")
            lines.append("")

        # Community directory
        if communities:
            lines.append("## Community Directory")
            lines.append("")
            for community in communities:
                label = community.label or f"Community {community.id}"
                link = self.community_link(link_index, community.id, label)
                lines.append(f"- {link} — {community.size} memories")
            lines.append("")

        # God nodes (highly connected central memories)
        if god_nodes:
            lines.append("## Central Nodes")
            lines.append("")
            lines.append("Highly connected memories that bridge multiple topics:")
            lines.append("")
            for node in god_nodes:
                title = node_titles.get(node.memory_id, node.memory_id[:16])
                link = self.entity_link(link_index, node.memory_id, title)
                lines.append(f"- {link} (degree: {node.degree}, community: {node.community_id})")
            lines.append("")

        return "\n".join(lines)

    def render_community(
        self,
        community: Community,
        summary: str,
        members: list[dict],
        bridges: list[Bridge],
        source_docs: list[str] | None = None,
        link_index: LinkIndex | None = None,
    ) -> str:
        """Render a community article.

        Args:
            community: Community model with id, size, cohesion_score, label
            summary: LLM-generated or fallback summary text
            members: List of dicts with 'id', 'content', 'type' for top members
            bridges: Cross-community bridge edges involving this community
            source_docs: Optional list of source document titles/IDs

        Returns:
            Markdown string for ``communities/community-{id}.md``
        """
        label = community.label or f"Community {community.id}"
        lines: list[str] = []

        lines.append(f"# {label}")
        lines.append("")
        lines.append(f"**Size:** {community.size} memories  ")
        lines.append(f"**Cohesion:** {community.cohesion_score:.2f}")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(summary or "_No summary available._")
        lines.append("")

        # Top members
        if members:
            lines.append("## Key Memories")
            lines.append("")
            # Numbered to match the [m<n>] references in the Summary (skip empties +
            # number consecutively, exactly as the summary's member block does).
            shown = 0
            for mem in members:
                content = (mem.get("content") or "").strip()
                if not content:
                    continue
                shown += 1
                if shown > 10:
                    break
                mem_type = mem.get("type", "memory")
                content_preview = content[:120].replace("\n", " ")
                lines.append(f"- **[m{shown}]** _[{mem_type}]_ {content_preview}")
            lines.append("")

        # Cross-community bridges
        if bridges:
            lines.append("## Connections to Other Communities")
            lines.append("")
            seen_communities: set[int] = set()
            neighbours: list[tuple[int, str, str, float]] = []
            for bridge in bridges:
                other_id = bridge.target_community_id if bridge.source_community_id == community.id else bridge.source_community_id
                if other_id not in seen_communities:
                    seen_communities.add(other_id)
                    other_label = f"Community {other_id}"
                    link = self.community_link(link_index, other_id, other_label)
                    lines.append(f"- {link} via `{bridge.relationship_type}` (strength: {bridge.strength:.2f})")
                    neighbours.append(
                        (other_id, other_label, bridge.relationship_type, bridge.strength)
                    )
            lines.append("")

            # The bullets above are the complete record; this shows its shape. Omitted
            # entirely if the assembled diagram does not validate -- a broken fence
            # renders as an error block, which is worse than no picture.
            diagram = build_community_flowchart(community.id, label, neighbours)
            if diagram:
                lines.append(diagram)
                lines.append("")

        # Source documents
        if source_docs:
            lines.append("## Source Documents")
            lines.append("")
            for doc in source_docs:
                lines.append(f"- {doc}")
            lines.append("")

        return "\n".join(lines)

    def render_entity(
        self,
        entity_id: str,
        title: str,
        entity_card: dict | None,
        connections: list[dict],
        community: Community | None,
        source_memories: list[dict],
        link_index: LinkIndex | None = None,
    ) -> str:
        """Render an entity deep-dive article.

        Args:
            entity_id: Entity / memory ID
            title: Display title for the entity
            entity_card: Optional dict with 'insights' list of strings
            connections: List of dicts with 'target_id', 'relationship', 'strength'
            community: Community this entity belongs to (for back-link)
            source_memories: List of dicts with 'id', 'content', 'type'

        Returns:
            Markdown string for ``entities/{slug}.md``
        """
        lines: list[str] = []

        lines.append(f"# {title}")
        lines.append("")
        lines.append(f"**Entity ID:** `{entity_id}`")
        if community is not None:
            community_label = community.label or f"Community {community.id}"
            lines.append(
                f"**Community:** {self.community_link(link_index, community.id, community_label)}"
            )
        lines.append("")

        # Entity insights
        if entity_card and entity_card.get("insights"):
            lines.append("## Insights")
            lines.append("")
            for insight in entity_card["insights"]:
                lines.append(f"- {insight}")
            lines.append("")

        # Connections grouped by relationship
        if connections:
            lines.append("## Connections")
            lines.append("")
            by_rel: dict[str, list[dict]] = {}
            for conn in connections:
                rel = conn.get("relationship", "related")
                if rel not in by_rel:
                    by_rel[rel] = []
                by_rel[rel].append(conn)

            for rel, conns in sorted(by_rel.items()):
                lines.append(f"### {rel.replace('_', ' ').title()}")
                lines.append("")
                for conn in conns[:10]:
                    target_id = conn.get("target_id", "")
                    target_display = conn.get("target_title") or target_id[:16]
                    strength = conn.get("strength", 0.0)
                    link = self.entity_link(link_index, target_id, target_display)
                    lines.append(f"- {link} (strength: {strength:.2f})")
                lines.append("")

        # Source memories — numbered to match the [m<n>] references in the summary
        # (skip empties + number consecutively, exactly as the member block does).
        if source_memories:
            lines.append("## Source Memories")
            lines.append("")
            shown = 0
            for mem in source_memories:
                content = (mem.get("content") or "").strip()
                if not content:
                    continue
                shown += 1
                if shown > 10:
                    break
                mem_type = mem.get("type", "memory")
                content_preview = content[:200].replace("\n", " ")
                lines.append(f"- **[m{shown}]** _[{mem_type}]_ {content_preview}")
            lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # Utility helpers
    # ------------------------------------------------------------------ #

    def slugify(self, name: str) -> str:
        """Convert a name to a safe filename slug.

        Replaces spaces, slashes, colons, and other special characters
        with hyphens and lowercases the result.

        Args:
            name: Input string

        Returns:
            URL/filename-safe slug
        """
        slug = name.lower()
        slug = re.sub(r"[/\\:]+", "-", slug)
        slug = re.sub(r"[^a-z0-9\-_]", "-", slug)
        slug = re.sub(r"-{2,}", "-", slug)
        slug = slug.strip("-")
        return slug or "unknown"

    def maybe_wikilink(self, target: str | None, display: str) -> str:
        """A wikilink when ``target`` resolves, otherwise plain display text.

        The renderer knows a reference exists (a bridge, an association) but not
        whether an ARTICLE was produced for it — capped runs and filtered
        communities mean many referenced things have no page. Emitting a link
        anyway produces a dangling reference, so an unresolved target degrades to
        text: the relationship is still shown, it just isn't clickable.
        """
        if not target:
            return display
        return self.wikilink(target, display)

    def community_link(self, link_index: LinkIndex | None, community_id: int, display: str) -> str:
        """Link to a community article if this run produced one."""
        return self.maybe_wikilink(
            link_index.community_path(community_id) if link_index else None, display
        )

    def entity_link(self, link_index: LinkIndex | None, key: str | None, display: str) -> str:
        """Link to an entity article if this run produced one for ``key``."""
        return self.maybe_wikilink(
            link_index.entity_path(key) if link_index else None, display
        )

    def wikilink(self, target: str, display: str | None = None) -> str:
        """Format an Obsidian wikilink.

        Args:
            target: Link target (filename without .md extension, or path)
            display: Optional display text; if None the target is used as-is

        Returns:
            ``[[target]]`` or ``[[target|display]]``
        """
        if display and display != target:
            return f"[[{target}|{display}]]"
        return f"[[{target}]]"

    def render_frontmatter(self, fields: dict) -> str:
        """Render a leading YAML frontmatter block (Obsidian properties).

        ``fields`` values may be scalars (str/int/float/bool) or lists of scalars;
        ``None`` values and empty lists are skipped. Returns ``""`` when there is
        nothing to render (so callers can unconditionally prepend it). Keys are
        emitted in insertion order.
        """
        if not fields:
            return ""
        lines = ["---"]
        for key, value in fields.items():
            if value is None:
                continue
            if isinstance(value, (list, tuple)):
                items = [self._yaml_scalar(v) for v in value if v is not None]
                if not items:
                    continue
                lines.append(f"{key}: [{', '.join(items)}]")
            else:
                lines.append(f"{key}: {self._yaml_scalar(value)}")
        if len(lines) == 1:  # only the opening '---' — nothing emitted
            return ""
        lines.append("---")
        lines.append("")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _yaml_scalar(value) -> str:
        """Format a scalar for YAML, quoting strings that need it."""
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            return str(value)
        s = str(value)
        # Quote when the string carries YAML-significant characters or leading/
        # trailing space; escape embedded double quotes.
        if s == "" or s != s.strip() or any(c in s for c in ':#[]{},&*!|>\'"%@`') or s[0] in "-?":
            return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
        return s
