"""Obsidian-compatible markdown renderer for knowledgebase articles."""

import re

from ...models.graph_analysis import Bridge, CentralNode, Community, GraphStats


class ObsidianRenderer:
    """Renders knowledgebase articles in Obsidian-compatible Markdown.

    Uses [[wikilink]] syntax for cross-references so that articles
    open correctly inside an Obsidian vault.
    """

    # ------------------------------------------------------------------ #
    # Public rendering methods
    # ------------------------------------------------------------------ #

    def render_index(
        self,
        workspace_name: str,
        stats: GraphStats | None,
        communities: list[Community],
        god_nodes: list[CentralNode],
        node_titles: dict[str, str] | None = None,
    ) -> str:
        """Render the workspace index article.

        Args:
            workspace_name: Human-readable workspace name
            stats: Optional graph statistics block
            communities: List of detected communities
            god_nodes: Central nodes with high degree/betweenness
            node_titles: Optional mapping of memory_id -> display title for god nodes

        Returns:
            Markdown string for ``index.md``
        """
        node_titles = node_titles or {}
        lines: list[str] = []

        lines.append(f"# {workspace_name}")
        lines.append("")
        lines.append("> This knowledgebase was auto-generated by MemoryLayer.")
        lines.append("")

        # Stats block
        if stats:
            lines.append("## Graph Overview")
            lines.append("")
            lines.append("| Metric | Value |")
            lines.append("|--------|-------|")
            lines.append(f"| Memories (nodes) | {stats.node_count} |")
            lines.append(f"| Associations (edges) | {stats.edge_count} |")
            lines.append(f"| Communities | {stats.community_count} |")
            lines.append(f"| Graph density | {stats.density:.3f} |")
            lines.append(f"| Average connections | {stats.avg_degree:.1f} |")
            lines.append(f"| Central nodes | {stats.god_node_count} |")
            lines.append("")

        # Community directory
        if communities:
            lines.append("## Community Directory")
            lines.append("")
            for community in communities:
                label = community.label or f"Community {community.id}"
                slug = f"community-{community.id}"
                link = self.wikilink(f"communities/{slug}", label)
                lines.append(f"- {link} — {community.size} memories")
            lines.append("")

        # God nodes (highly connected central memories)
        if god_nodes:
            lines.append("## Central Nodes")
            lines.append("")
            lines.append("Highly connected memories that bridge multiple topics:")
            lines.append("")
            for node in god_nodes:
                title = node_titles.get(node.memory_id, node.memory_id[:16])
                slug = self.slugify(title)
                link = self.wikilink(f"entities/{slug}", title)
                lines.append(f"- {link} (degree: {node.degree}, community: {node.community_id})")
            lines.append("")

        return "\n".join(lines)

    def render_community(
        self,
        community: Community,
        summary: str,
        members: list[dict],
        bridges: list[Bridge],
        source_docs: list[str] | None = None,
    ) -> str:
        """Render a community article.

        Args:
            community: Community model with id, size, cohesion_score, label
            summary: LLM-generated or fallback summary text
            members: List of dicts with 'id', 'content', 'type' for top members
            bridges: Cross-community bridge edges involving this community
            source_docs: Optional list of source document titles/IDs

        Returns:
            Markdown string for ``communities/community-{id}.md``
        """
        label = community.label or f"Community {community.id}"
        lines: list[str] = []

        lines.append(f"# {label}")
        lines.append("")
        lines.append(f"**Size:** {community.size} memories  ")
        lines.append(f"**Cohesion:** {community.cohesion_score:.2f}")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(summary or "_No summary available._")
        lines.append("")

        # Top members
        if members:
            lines.append("## Key Memories")
            lines.append("")
            for mem in members[:10]:
                content_preview = (mem.get("content") or "")[:120].replace("\n", " ")
                mem_type = mem.get("type", "memory")
                lines.append(f"- **[{mem_type}]** {content_preview}")
            lines.append("")

        # Cross-community bridges
        if bridges:
            lines.append("## Connections to Other Communities")
            lines.append("")
            seen_communities: set[int] = set()
            for bridge in bridges:
                other_id = bridge.target_community_id if bridge.source_community_id == community.id else bridge.source_community_id
                if other_id not in seen_communities:
                    seen_communities.add(other_id)
                    other_slug = f"community-{other_id}"
                    link = self.wikilink(f"communities/{other_slug}", f"Community {other_id}")
                    lines.append(f"- {link} via `{bridge.relationship_type}` (strength: {bridge.strength:.2f})")
            lines.append("")

        # Source documents
        if source_docs:
            lines.append("## Source Documents")
            lines.append("")
            for doc in source_docs:
                lines.append(f"- {doc}")
            lines.append("")

        return "\n".join(lines)

    def render_entity(
        self,
        entity_id: str,
        title: str,
        entity_card: dict | None,
        connections: list[dict],
        community: Community | None,
        source_memories: list[dict],
    ) -> str:
        """Render an entity deep-dive article.

        Args:
            entity_id: Entity / memory ID
            title: Display title for the entity
            entity_card: Optional dict with 'insights' list of strings
            connections: List of dicts with 'target_id', 'relationship', 'strength'
            community: Community this entity belongs to (for back-link)
            source_memories: List of dicts with 'id', 'content', 'type'

        Returns:
            Markdown string for ``entities/{slug}.md``
        """
        lines: list[str] = []

        lines.append(f"# {title}")
        lines.append("")
        lines.append(f"**Entity ID:** `{entity_id}`")
        if community is not None:
            community_label = community.label or f"Community {community.id}"
            community_slug = f"community-{community.id}"
            lines.append(f"**Community:** {self.wikilink(f'communities/{community_slug}', community_label)}")
        lines.append("")

        # Entity insights
        if entity_card and entity_card.get("insights"):
            lines.append("## Insights")
            lines.append("")
            for insight in entity_card["insights"]:
                lines.append(f"- {insight}")
            lines.append("")

        # Connections grouped by relationship
        if connections:
            lines.append("## Connections")
            lines.append("")
            by_rel: dict[str, list[dict]] = {}
            for conn in connections:
                rel = conn.get("relationship", "related")
                if rel not in by_rel:
                    by_rel[rel] = []
                by_rel[rel].append(conn)

            for rel, conns in sorted(by_rel.items()):
                lines.append(f"### {rel.replace('_', ' ').title()}")
                lines.append("")
                for conn in conns[:10]:
                    target_display = conn.get("target_title") or conn.get("target_id", "")[:16]
                    target_slug = self.slugify(target_display)
                    strength = conn.get("strength", 0.0)
                    link = self.wikilink(f"entities/{target_slug}", target_display)
                    lines.append(f"- {link} (strength: {strength:.2f})")
                lines.append("")

        # Source memories
        if source_memories:
            lines.append("## Source Memories")
            lines.append("")
            for mem in source_memories[:10]:
                content_preview = (mem.get("content") or "")[:200].replace("\n", " ")
                mem_type = mem.get("type", "memory")
                lines.append(f"- **[{mem_type}]** {content_preview}")
            lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # Utility helpers
    # ------------------------------------------------------------------ #

    def slugify(self, name: str) -> str:
        """Convert a name to a safe filename slug.

        Replaces spaces, slashes, colons, and other special characters
        with hyphens and lowercases the result.

        Args:
            name: Input string

        Returns:
            URL/filename-safe slug
        """
        slug = name.lower()
        slug = re.sub(r"[/\\:]+", "-", slug)
        slug = re.sub(r"[^a-z0-9\-_]", "-", slug)
        slug = re.sub(r"-{2,}", "-", slug)
        slug = slug.strip("-")
        return slug or "unknown"

    def wikilink(self, target: str, display: str | None = None) -> str:
        """Format an Obsidian wikilink.

        Args:
            target: Link target (filename without .md extension, or path)
            display: Optional display text; if None the target is used as-is

        Returns:
            ``[[target]]`` or ``[[target|display]]``
        """
        if display and display != target:
            return f"[[{target}|{display}]]"
        return f"[[{target}]]"
